#!/bin/sh

if command -v nvim >/dev/null; then
    nvim "$@"
elif command -v vim >/dev/null; then
    vim "$@"
elif command -v vi >/dev/null; then
    vi "$@"
elif command -v cpm >/dev/null; then
    cpm i neovim && nvim "$@"
else
    >&2 echo "you're system is broke"
    exit 1
fi
