#!/bin/sh

if command -v nvim >/dev/null; then
    nvim $@
elif command -v vim >/dev/null; then
    vim $@
else
    if command -v cpm >/dev/null; then
        cpm i neovim && nvim $@
    else
        >&2 echo "your system is broke"
        exit 1
    fi
fi
